name: Docker

on:
  push:
    # branches: ["main"]
    branches:
      - main
      - 'feature/**'
env:
  IMAGE_NAME: silverbullet
  # change namespaces before merging to silverbullet main branch
  NAMESPACE_GITHUB: sweisgerber
  NAMESPACE_DOCKER: sweisgerber
jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-arch builds with buildx
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Deno
        uses: denoland/setup-deno@d4873ceeec10de6275fecd1f94b6985369d40231
        with:
          deno-version: v1.32.5

      - name: Run bundle build
        run: |
          deno task build
          deno task bundle

      - name: Login to Docker Hub
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the ghcr Container registry
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #
      # MetaData Extract Docu: <https://github.com/docker/metadata-action>
      #
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: |
            # See the 2 different image names(paces) for docker-hub & ghcr
            ${{ env.NAMESPACE_DOCKER }}/${{ env.IMAGE_NAME }}
            ghcr.io/${{ env.NAMESPACE_GITHUB }}/${{ env.IMAGE_NAME }}
          tags: |
            # <https://github.com/docker/metadata-action#typeref>
            # minimal (short sha)
            type=sha,enable=true,priority=100,prefix=commit-,suffix=,format=short
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # tag w/ full tag part of git tag: <https://github.com/docker/metadata-action#typesemver>
            type=semver,pattern={{raw}},enable=true
            type=edge,branch=main # usually this would be the develop branch
            # defaults
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
